<a href="https://colab.research.google.com/github/Yoshitha61/PP/blob/main/Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Datasets and their operations.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/car-sales-extended-missing-data.csv')
data

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [ ]:
data.head(20)

      Make Colour  Odometer (KM)  Doors    Price
0    Honda  White        35431.0    4.0  15323.0
1      BMW   Blue       192714.0    5.0  19943.0
2    Honda  White        84714.0    4.0  28343.0
3   Toyota  White       154365.0    4.0  13434.0
4   Nissan   Blue       181577.0    3.0  14043.0
5    Honda    Red        42652.0    4.0  23883.0
6   Toyota   Blue       163453.0    4.0   8473.0
7    Honda  White            NaN    4.0  20306.0
8      NaN  White       130538.0    4.0   9374.0
9    Honda   Blue        51029.0    4.0  26683.0
10  Nissan  White       167421.0    4.0  16259.0
11  Nissan  Green        17119.0    4.0   6160.0
12  Nissan  White       102303.0    4.0  16909.0
13     NaN  White       134181.0    4.0  11121.0
14   Honda   Blue       199833.0    4.0  18946.0
15  Toyota   Blue       205592.0    4.0  16290.0
16  Toyota    Red        96742.0    4.0  34465.0
17     BMW  White       194189.0    5.0  17177.0
18  Nissan  White        67991.0    3.0   9109.0
19  Nissan   Blue       215820.0    4.0   6010.0

In [ ]:
df=pd.DataFrame(data)
da=df
df.head(30)

      Make Colour  Odometer (KM)  Doors    Price
0    Honda  White        35431.0    4.0  15323.0
1      BMW   Blue       192714.0    5.0  19943.0
2    Honda  White        84714.0    4.0  28343.0
3   Toyota  White       154365.0    4.0  13434.0
4   Nissan   Blue       181577.0    3.0  14043.0
5    Honda    Red        42652.0    4.0  23883.0
6   Toyota   Blue       163453.0    4.0   8473.0
7    Honda  White            NaN    4.0  20306.0
8      NaN  White       130538.0    4.0   9374.0
9    Honda   Blue        51029.0    4.0  26683.0
10  Nissan  White       167421.0    4.0  16259.0
11  Nissan  Green        17119.0    4.0   6160.0
12  Nissan  White       102303.0    4.0  16909.0
13     NaN  White       134181.0    4.0  11121.0
14   Honda   Blue       199833.0    4.0  18946.0
15  Toyota   Blue       205592.0    4.0  16290.0
16  Toyota    Red        96742.0    4.0  34465.0
17     BMW  White       194189.0    5.0  17177.0
18  Nissan  White        67991.0    3.0   9109.0
19  Nissan   Blue       215820.0    4.0   6010.0
20  Toyota    NaN       124844.0    4.0  24130.0
21   Honda    NaN        30615.0    4.0  29653.0
22  Toyota  White       148744.0    4.0  22489.0
23   Honda  Green       130075.0    4.0  21242.0
24   Honda   Blue       172718.0    4.0  14274.0
25   Honda   Blue       125819.0    4.0  15686.0
26   Honda  White       180390.0    4.0  13344.0
27   Honda  Green        82783.0    4.0  10984.0
28   Honda  White        56687.0    4.0   6135.0
29  Toyota  White       112004.0    4.0  13586.0

In [ ]:
drop=df.dropna()
drop.head(30)

      Make Colour  Odometer (KM)  Doors    Price
0    Honda  White        35431.0    4.0  15323.0
1      BMW   Blue       192714.0    5.0  19943.0
2    Honda  White        84714.0    4.0  28343.0
3   Toyota  White       154365.0    4.0  13434.0
4   Nissan   Blue       181577.0    3.0  14043.0
5    Honda    Red        42652.0    4.0  23883.0
6   Toyota   Blue       163453.0    4.0   8473.0
9    Honda   Blue        51029.0    4.0  26683.0
10  Nissan  White       167421.0    4.0  16259.0
11  Nissan  Green        17119.0    4.0   6160.0
12  Nissan  White       102303.0    4.0  16909.0
14   Honda   Blue       199833.0    4.0  18946.0
15  Toyota   Blue       205592.0    4.0  16290.0
16  Toyota    Red        96742.0    4.0  34465.0
17     BMW  White       194189.0    5.0  17177.0
18  Nissan  White        67991.0    3.0   9109.0
19  Nissan   Blue       215820.0    4.0   6010.0
22  Toyota  White       148744.0    4.0  22489.0
23   Honda  Green       130075.0    4.0  21242.0
24   Honda   Blue       172718.0    4.0  14274.0
25   Honda   Blue       125819.0    4.0  15686.0
26   Honda  White       180390.0    4.0  13344.0
27   Honda  Green        82783.0    4.0  10984.0
28   Honda  White        56687.0    4.0   6135.0
29  Toyota  White       112004.0    4.0  13586.0
30  Nissan   Blue        34024.0    4.0  23929.0
32  Nissan  White       203795.0    4.0   9330.0
33  Nissan  Green       153554.0    3.0   9780.0
34   Honda   Blue        71949.0    4.0  17516.0
35   Honda   Blue       191622.0    4.0   8738.0

In [ ]:
df.dropna(inplace=True)
df.head(30)

      Make Colour  Odometer (KM)  Doors    Price
0    Honda  White        35431.0    4.0  15323.0
1      BMW   Blue       192714.0    5.0  19943.0
2    Honda  White        84714.0    4.0  28343.0
3   Toyota  White       154365.0    4.0  13434.0
4   Nissan   Blue       181577.0    3.0  14043.0
5    Honda    Red        42652.0    4.0  23883.0
6   Toyota   Blue       163453.0    4.0   8473.0
9    Honda   Blue        51029.0    4.0  26683.0
10  Nissan  White       167421.0    4.0  16259.0
11  Nissan  Green        17119.0    4.0   6160.0
12  Nissan  White       102303.0    4.0  16909.0
14   Honda   Blue       199833.0    4.0  18946.0
15  Toyota   Blue       205592.0    4.0  16290.0
16  Toyota    Red        96742.0    4.0  34465.0
17     BMW  White       194189.0    5.0  17177.0
18  Nissan  White        67991.0    3.0   9109.0
19  Nissan   Blue       215820.0    4.0   6010.0
22  Toyota  White       148744.0    4.0  22489.0
23   Honda  Green       130075.0    4.0  21242.0
24   Honda   Blue       172718.0    4.0  14274.0
25   Honda   Blue       125819.0    4.0  15686.0
26   Honda  White       180390.0    4.0  13344.0
27   Honda  Green        82783.0    4.0  10984.0
28   Honda  White        56687.0    4.0   6135.0
29  Toyota  White       112004.0    4.0  13586.0
30  Nissan   Blue        34024.0    4.0  23929.0
32  Nissan  White       203795.0    4.0   9330.0
33  Nissan  Green       153554.0    3.0   9780.0
34   Honda   Blue        71949.0    4.0  17516.0
35   Honda   Blue       191622.0    4.0   8738.0

In [ ]:
df['Price']

0      15323.0
1      19943.0
2      28343.0
3      13434.0
4      14043.0
        ...
994    31666.0
995    32042.0
997    31570.0
998     4001.0
999    12732.0
Name: Price, Length: 773, dtype: float64

In [ ]:
df['Price'].dropna()

0      15323.0
1      19943.0
2      28343.0
3      13434.0
4      14043.0
        ...
994    31666.0
995    32042.0
997    31570.0
998     4001.0
999    12732.0
Name: Price, Length: 773, dtype: float64

In [ ]:
df.loc[:,['Colour','Price']] //without nan values

    Colour    Price
0    White  15323.0
1     Blue  19943.0
2    White  28343.0
3    White  13434.0
4     Blue  14043.0
..     ...      ...
994   Blue  31666.0
995  Black  32042.0
997   Blue  31570.0
998  White   4001.0
999   Blue  12732.0

[773 rows x 2 columns]

In [ ]:
da.fillna('Missing')
da.head(20)

      Make Colour  Odometer (KM)  Doors    Price
0    Honda  White        35431.0    4.0  15323.0
1      BMW   Blue       192714.0    5.0  19943.0
2    Honda  White        84714.0    4.0  28343.0
3   Toyota  White       154365.0    4.0  13434.0
4   Nissan   Blue       181577.0    3.0  14043.0
5    Honda    Red        42652.0    4.0  23883.0
6   Toyota   Blue       163453.0    4.0   8473.0
7    Honda  White            NaN    4.0  20306.0
8      NaN  White       130538.0    4.0   9374.0
9    Honda   Blue        51029.0    4.0  26683.0
10  Nissan  White       167421.0    4.0  16259.0
11  Nissan  Green        17119.0    4.0   6160.0
12  Nissan  White       102303.0    4.0  16909.0
13     NaN  White       134181.0    4.0  11121.0
14   Honda   Blue       199833.0    4.0  18946.0
15  Toyota   Blue       205592.0    4.0  16290.0
16  Toyota    Red        96742.0    4.0  34465.0
17     BMW  White       194189.0    5.0  17177.0
18  Nissan  White        67991.0    3.0   9109.0
19  Nissan   Blue       215820.0    4.0   6010.0